### ISSUE TITLE
About build events 

### ISSUE THREAD

**Issue by chucklu** [HearthSim/HearthMirror#1]
if exist $(ProjectDir)hsdata (
  git -C $(ProjectDir)hsdata fetch
  git -C $(ProjectDir)hsdata reset --hard origin/master
) else (
  git clone --depth=1 https://github.com/HearthSim/hsdata.git $(ProjectDir)hsdata
)
if "$(ConfigurationName)" == "Release" (
  powershell -ExecutionPolicy Unrestricted -file $(ProjectDir)verify.ps1 $(ProjectDir)
)
xcopy /Y "$(ProjectDir)hsdata\CardDefs.xml" "$(ProjectDir)CardDefs.xml*"

**Comment by chucklu** [comment]
To add into PATH:
Right-Click on My Computer.
Click on Advanced System Settings.
Click on Environment Variables.
Then, under System Variables, look for the path variable and click edit.
Add the path to git's bin and cmd at the end of the string like this: ;C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd.

**Comment by chucklu** [comment]
maybe,you can add this to the readme.md

**Comment by chucklu** [comment]
git -C
I have Googled this ,can not find the option for -c,what does this mean?

**Comment by riQQ** [comment]
`-C <path>: Run as if git was started in <path> instead of the current working directory.` (https://git-scm.com/docs/git)

**Comment by azeier** [comment]
I don't think this needs to be in the readme. Having git in `PATH` should be pretty standard, and otherwise it's an error that's rather easy to figure out with google.

**Comment by chucklu** [comment]
@riQQ  thank you

**Comment by andburn** [comment]
@azeier Something could go in the FAQ. For example GitHub Desktop is popular on Windows and uses [posh-git](https://github.com/dahlbyk/posh-git) (powershell) as the shell, so git isn't on the system path for msbuild. If you only used the UI, it wouldn't be entirely obvious. Also, zip may not be on the path either :stuck_out_tongue_winking_eye:
