### ISSUE TITLE
Linux/Wine support

### ISSUE THREAD

**Issue by garar** [HearthSim/HearthMirror#18]
Hi guys!

I just found this library, it looks great. Do you have any plans on supporting Linux in the Cpp port?

Thanks for all the great work!

**Comment by ifeherva** [comment]
Yes, the moment HS will run _natively_ on Linux.

**Comment by jleclanche** [comment]
@ifeherva i think if it's compiled and run in wine itself there's no reason why it couldn't attach to the hs wine process.

**Comment by ifeherva** [comment]
@jleclanche then you can run the windows version already in wine, no need for the port.

**Comment by jleclanche** [comment]
Right, that's what I mean.
