### ISSUE TITLE
[Question] HearthMirror in Python

### ISSUE THREAD

**Issue by gcardozo123** [HearthSim/HearthMirror#26]
Hi,

Do you know of any Python module that would be equivalent or similar to HearthMirror?
Sorry for asking this question here. 

Thanks for your time!

**Comment by jleclanche** [comment]
HearthMirror is the only open implementation of Hearthstone memory reading. There is a c++ branch in this repo, if you want to generate Python bindings feel free although it'll be a lot of work.

**Comment by gcardozo123** [comment]
Is there any other way to obtain the player's collection (besides reading the HS memory)?

**Comment by jleclanche** [comment]
Nope
