### ISSUE TITLE
About Card class

### ISSUE THREAD

**Issue by SelaO** [HearthSim/HearthMirror#28]
I want to get the class choices when starting arena, is the function here: https://github.com/HearthSim/HearthMirror/blob/a199ec046dc765889db3d645a317cf6c62fa8280/HearthMirror/Reflection.cs#L331 

Is that what I need? And if so, is the class `Card` used to identify heroes and cards?

**Comment by ceceita** [comment]
looking around i found this
https://github.com/rembound/Arena-Helper/blob/548091efa2441291be491e899f9e73221562572b/Plugin.cs#L1291
to me [ a hello world user ] seems like where the detection is made , but dont trust me :)

**Comment by SelaO** [comment]
Yes I got to this function, I want to do have a similar functionality, it's just a little strange that `Card` holds hero info.

**Comment by azeier** [comment]
Heroes are considered cards in Hearthstone.
